name: news_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  change_app_package_name: ^1.1.0
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  freezed_annotation: ^2.4.1
  go_router: ^11.1.4
  google_fonts: ^6.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.2.0
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - shorebird.yaml
